% IEEE 33-bus resilience restoration with communication coupling (YALMIP)
% This script builds a multi-period MILP for post-typhoon restoration and
% compares communication-aware vs. communication-agnostic cases.
%
% Requirements: YALMIP, MILP solver (Gurobi recommended).
%
% Author: autogenerated

clear; clc;

%% Settings
T = 6;                 % hours
Delta_t = 1;           % hour
baseMVA = 1;           % use kW base (1 MVA = 1000 kW -> treat as kW base here)
V0 = 1.0;              % substation voltage (p.u.)
Vmin = 0.95;
Vmax = 1.05;

max_switch_ops_per_hour = 2; % engineering rule
max_tie_closed = 1;          % radiality simplification

rng(1);

%% IEEE 33-bus line data (from, to, R, X, normally closed)
% Standard data in per-unit on 12.66 kV base, here kept as relative values.
lines = [
     1  2  0.0922 0.0470 1
     2  3  0.4930 0.2511 1
     3  4  0.3660 0.1864 1
     4  5  0.3811 0.1941 1
     5  6  0.8190 0.7070 1
     6  7  0.1872 0.6188 1
     7  8  1.7114 1.2351 1
     8  9  1.0300 0.7400 1
     9 10  1.0440 0.7400 1
    10 11  0.1966 0.0650 1
    11 12  0.3744 0.1238 1
    12 13  1.4680 1.1550 1
    13 14  0.5416 0.7129 1
    14 15  0.5910 0.5260 1
    15 16  0.7463 0.5450 1
    16 17  1.2890 1.7210 1
    17 18  0.7320 0.5740 1
    18 19  0.1640 0.1565 1
    19 20  1.5042 1.3554 1
    20 21  0.4095 0.4784 1
    21 22  0.7089 0.9373 1
    22 23  0.4512 0.3083 1
    23 24  0.8980 0.7091 1
    24 25  0.8960 0.7011 1
    25 26  0.2030 0.1034 1
    26 27  0.2842 0.1447 1
    27 28  1.0590 0.9337 1
    28 29  0.8042 0.7006 1
    29 30  0.5075 0.2585 1
    30 31  0.9744 0.9630 1
    31 32  0.3105 0.3619 1
    32 33  0.3410 0.5302 1
];

% Tie switches (normally open)
ties = [
    33  8  0.0 0.0 0
     9 15  0.0 0.0 0
    12 22  0.0 0.0 0
    18 33  0.0 0.0 0
    25 29  0.0 0.0 0
];

lines = [lines; ties];
L = size(lines,1);
nb = 33;

from = lines(:,1);
to = lines(:,2);
R = lines(:,3);
X = lines(:,4);
normal_closed = lines(:,5);

%% Load data (kW, kVar) from standard IEEE 33
load_data = zeros(nb,2);
load_data(2,:)  = [100 60];
load_data(3,:)  = [90 40];
load_data(4,:)  = [120 80];
load_data(5,:)  = [60 30];
load_data(6,:)  = [60 20];
load_data(7,:)  = [200 100];
load_data(8,:)  = [200 100];
load_data(9,:)  = [60 20];
load_data(10,:) = [60 20];
load_data(11,:) = [45 30];
load_data(12,:) = [60 35];
load_data(13,:) = [60 35];
load_data(14,:) = [120 80];
load_data(15,:) = [60 10];
load_data(16,:) = [60 20];
load_data(17,:) = [60 20];
load_data(18,:) = [90 40];
load_data(19,:) = [90 40];
load_data(20,:) = [90 40];
load_data(21,:) = [90 40];
load_data(22,:) = [90 40];
load_data(23,:) = [90 50];
load_data(24,:) = [420 200];
load_data(25,:) = [420 200];
load_data(26,:) = [60 25];
load_data(27,:) = [60 25];
load_data(28,:) = [60 20];
load_data(29,:) = [120 70];
load_data(30,:) = [200 600];
load_data(31,:) = [150 70];
load_data(32,:) = [210 100];
load_data(33,:) = [60 40];

P_load = load_data(:,1);
Q_load = load_data(:,2);

%% Resource placement
% DG at bus 6
DG.bus = 6;
DG.Pmax = 600; % kW
DG.Qmax = 300;

% PV at bus 18
PV.bus = 18;
PV.Prated = 400; % kW

% WT at bus 30
WT.bus = 30;
WT.Prated = 500; % kW

% ESS at bus 25
ESS.bus = 25;
ESS.Pmax = 300;   % kW
ESS.Emax = 600;   % kWh
ESS.SOC0 = 0.60;  % 60%
ESS.SOCmin = 0.20;
ESS.SOCmax = 0.90;

%% Critical loads
critical_buses = [3 14 18 25 30];
omega = ones(nb,1);
omega(critical_buses) = 3;

%% Switch control map (sectionalizing + ties)
% Indices of controllable switches (line list indices)
% Sectionalizing: 6-7, 13-14, 20-21, 24-25, 29-30
% Ties: 33-8, 9-15, 12-22, 18-33, 25-29
section_lines = find((from==6 & to==7) | (from==13 & to==14) | (from==20 & to==21) | ...
                      (from==24 & to==25) | (from==29 & to==30));

tie_lines = find(normal_closed==0);
controllable_lines = unique([section_lines; tie_lines]);

%% Communication network
% Communication nodes (index)
comm_nodes = {'C1','C7','C14','C21','C25','C30','C6','C18','C33'}; % backbone + access
nC = numel(comm_nodes);

% Map comm node to bus (for power supply threshold)
comm_bus_map = containers.Map({'C1','C7','C14','C21','C25','C30','C6','C18','C33'}, ...
                              [1,7,14,21,25,30,6,18,33]);

% Backbone ring links (undirected base)
comm_links_undirected = {
    'C1','C7'
    'C7','C14'
    'C14','C21'
    'C21','C25'
    'C25','C30'
    'C30','C1'
    'C6','C7'
    'C18','C21'
    'C33','C30'
};
% Expand to directed edges
comm_links = [comm_links_undirected; cellfun(@(a,b) {b,a}, comm_links_undirected(:,1), comm_links_undirected(:,2))];

% Device src mapping
src_map = containers.Map();
src_map('DG') = 'C6';
src_map('PV') = 'C18';
src_map('WT') = 'C30';
src_map('ESS') = 'C25';

switch_src = containers.Map();
switch_src('S1') = 'C7';   % 6-7
switch_src('S2') = 'C14';  % 13-14
switch_src('S3') = 'C21';  % 20-21
switch_src('S4') = 'C25';  % 24-25
switch_src('S5') = 'C30';  % 29-30
switch_src('T1') = 'C33';  % 33-8
switch_src('T2') = 'C14';  % 9-15
switch_src('T3') = 'C21';  % 12-22
switch_src('T4') = 'C33';  % 18-33
switch_src('T5') = 'C25';  % 25-29

switch_line_ids = containers.Map();
switch_line_ids('S1') = find(from==6 & to==7);
switch_line_ids('S2') = find(from==13 & to==14);
switch_line_ids('S3') = find(from==20 & to==21);
switch_line_ids('S4') = find(from==24 & to==25);
switch_line_ids('S5') = find(from==29 & to==30);
switch_line_ids('T1') = find(from==33 & to==8);
switch_line_ids('T2') = find(from==9 & to==15);
switch_line_ids('T3') = find(from==12 & to==22);
switch_line_ids('T4') = find(from==18 & to==33);
switch_line_ids('T5') = find(from==25 & to==29);

%% Scenarios (faults, repairs, renewable availability)
scenarios = define_scenarios(T);

%% Cases
cases = {
    struct('name','A_no_comm','use_comm',false,'ring',true,'theta',0.8),
    struct('name','B_comm_ring','use_comm',true,'ring',true,'theta',0.8),
    struct('name','C_comm_tree','use_comm',true,'ring',false,'theta',0.8),
    struct('name','D_theta06','use_comm',true,'ring',true,'theta',0.6),
    struct('name','D_theta10','use_comm',true,'ring',true,'theta',1.0)
};

results = struct();

%% Main loop
for s = 1:numel(scenarios)
    scenario = scenarios{s};
    fprintf('Running scenario: %s\n', scenario.name);

    for c = 1:numel(cases)
        cfg = cases{c};
        fprintf('  Case: %s\n', cfg.name);
        res = solve_restoration(nb, L, from, to, R, X, normal_closed, ...
            P_load, Q_load, DG, PV, WT, ESS, ...
            critical_buses, omega, controllable_lines, tie_lines, ...
            switch_src, switch_line_ids, comm_nodes, comm_bus_map, comm_links, ...
            scenario, T, Delta_t, V0, Vmin, Vmax, baseMVA, ...
            cfg.use_comm, cfg.ring, cfg.theta, max_switch_ops_per_hour, max_tie_closed);
        results.(scenario.name).(cfg.name) = res;
    end
end

%% Post-processing (simple output)
fprintf('\nSummary (ENS):\n');
for s = 1:numel(scenarios)
    scenario = scenarios{s};
    fprintf('Scenario %s:\n', scenario.name);
    for c = 1:numel(cases)
        cfg = cases{c};
        res = results.(scenario.name).(cfg.name);
        fprintf('  %-12s ENS = %.2f kWh, R = %.4f\n', cfg.name, res.ENS, res.R);
    end
end

%% --- Local functions ---
function scenarios = define_scenarios(T)
    scenarios = {};
    % S1 light
    s1.name = 'S1_light';
    s1.line_faults = [8 9; 14 15];
    s1.line_repairs = [4 3]; % hour indices when repaired
    s1.comm_faults = {'C14','C21'}; % link C14-C21 down
    s1.comm_link_repair = 2;
    s1.pv_alpha = linspace(0.6,0.8,T);
    s1.wt_alpha = linspace(0.7,0.9,T);
    scenarios{end+1} = s1;

    % S2 medium
    s2.name = 'S2_medium';
    s2.line_faults = [5 6; 9 10; 15 16; 27 28];
    s2.line_repairs = [3 4 5 6];
    s2.comm_faults = {'C18','C21'; 'C25','C30'}; % links
    s2.comm_link_repair = [3 4];
    s2.pv_alpha = linspace(0.4,0.7,T);
    s2.wt_alpha = linspace(0.5,0.8,T);
    scenarios{end+1} = s2;

    % S3 heavy
    s3.name = 'S3_heavy';
    s3.line_faults = [2 3; 6 7; 13 14; 20 21; 24 25; 30 31];
    s3.line_repairs = [4 5 5 6 6 6];
    s3.comm_faults = {'C14','node'; 'C30','C1'}; % C14 node down, link C30-C1 down
    s3.comm_link_repair = [5 5];
    s3.pv_alpha = linspace(0.2,0.5,T);
    s3.wt_alpha = linspace(0.3,0.6,T);
    scenarios{end+1} = s3;
end

function res = solve_restoration(nb, L, from, to, R, X, normal_closed, ...
        P_load, Q_load, DG, PV, WT, ESS, ...
        critical_buses, omega, controllable_lines, tie_lines, ...
        switch_src, switch_line_ids, comm_nodes, comm_bus_map, comm_links, ...
        scenario, T, Delta_t, V0, Vmin, Vmax, baseMVA, ...
        use_comm, use_ring, theta, max_ops, max_tie_closed)

    % Variables
    P = sdpvar(L,T,'full');
    Q = sdpvar(L,T,'full');
    V = sdpvar(nb,T,'full');
    y = binvar(L,T,'full'); % line status

    lambda = sdpvar(nb,T,'full'); % load served ratio

    P_DG = sdpvar(1,T);
    Q_DG = sdpvar(1,T);
    P_PV = sdpvar(1,T);
    P_WT = sdpvar(1,T);
    P_ESS = sdpvar(1,T);
    SOC = sdpvar(1,T);

    % Communication variables
    s_comm = binvar(numel(comm_nodes),T,'full'); % comm node energized
    reach = binvar(numel(comm_nodes),T,'full');  % reachable from control center

    % Build availability for lines
    line_avail = ones(L,T);
    for k = 1:size(scenario.line_faults,1)
        f = scenario.line_faults(k,1);
        t = scenario.line_faults(k,2);
        idx = find(from==f & to==t);
        if ~isempty(idx)
            repair_t = scenario.line_repairs(k);
            line_avail(idx,1:repair_t-1) = 0;
        end
    end

    % Communication link availability
    comm_avail = ones(size(comm_links,1),T);
    for k = 1:size(scenario.comm_faults,1)
        c1 = scenario.comm_faults{k,1};
        c2 = scenario.comm_faults{k,2};
        if strcmp(c2,'node')
            continue;
        end
        idxs = find_link_idx(comm_links, c1, c2);
        if ~isempty(idxs)
            repair_t = scenario.comm_link_repair(k);
            comm_avail(idxs,1:repair_t-1) = 0;
        end
    end

    % Comm node availability (node damage)
    comm_node_avail = ones(numel(comm_nodes),T);
    for k = 1:size(scenario.comm_faults,1)
        c1 = scenario.comm_faults{k,1};
        c2 = scenario.comm_faults{k,2};
        if strcmp(c2,'node')
            idx = find(strcmp(comm_nodes,c1));
            repair_t = scenario.comm_link_repair(k);
            comm_node_avail(idx,1:repair_t-1) = 0;
        end
    end

    Constraints = [];

    % Voltage at slack
    Constraints = [Constraints, V(1,:) == V0];

    % Load ratio bounds
    Constraints = [Constraints, 0 <= lambda <= 1];

    % DG/PV/WT/ESS limits
    Constraints = [Constraints, 0 <= P_DG <= DG.Pmax];
    Constraints = [Constraints, -DG.Qmax <= Q_DG <= DG.Qmax];
    Constraints = [Constraints, 0 <= P_PV <= scenario.pv_alpha*PV.Prated];
    Constraints = [Constraints, 0 <= P_WT <= scenario.wt_alpha*WT.Prated];

    Constraints = [Constraints, -ESS.Pmax <= P_ESS <= ESS.Pmax];

    for t = 1:T
        if t == 1
            Constraints = [Constraints, SOC(t) == ESS.SOC0 + (P_ESS(t)*Delta_t)/ESS.Emax];
        else
            Constraints = [Constraints, SOC(t) == SOC(t-1) + (P_ESS(t)*Delta_t)/ESS.Emax];
        end
    end
    Constraints = [Constraints, ESS.SOCmin <= SOC <= ESS.SOCmax];

    % Line status constraints
    for t = 1:T
        for l = 1:L
            if ismember(l, controllable_lines)
                Constraints = [Constraints, y(l,t) <= line_avail(l,t)];
            else
                Constraints = [Constraints, y(l,t) == line_avail(l,t)];
            end
        end
    end

    % Tie lines open by default; allow at most max_tie_closed
    Constraints = [Constraints, sum(y(tie_lines,:),1) <= max_tie_closed];

    % Switch operation limit per hour (count changes)
    for t = 2:T
        Constraints = [Constraints, sum(abs(y(controllable_lines,t) - y(controllable_lines,t-1))) <= max_ops];
    end

    % Communication model
    if use_comm
        % Communication node energized if local load served above threshold and node available
        for t = 1:T
            for i = 1:numel(comm_nodes)
                bus = comm_bus_map(comm_nodes{i});
                Constraints = [Constraints, lambda(bus,t) >= theta*s_comm(i,t)];
                Constraints = [Constraints, s_comm(i,t) <= comm_node_avail(i,t)];
            end
        end

        % Connectivity constraints via flow from control center C1
        C1_idx = find(strcmp(comm_nodes,'C1'));
        nC = numel(comm_nodes);
        nL = size(comm_links,1);
        f = sdpvar(nL,T,'full');

        for t = 1:T
            % Flow bounds linked to link availability and node energization
            for e = 1:nL
                Constraints = [Constraints, -nC*comm_avail(e,t) <= f(e,t) <= nC*comm_avail(e,t)];
            end

            for i = 1:nC
                in = find_link_incidence(comm_links, comm_nodes, i, 'in');
                out = find_link_incidence(comm_links, comm_nodes, i, 'out');
                if i == C1_idx
                    Constraints = [Constraints, sum(f(out,t)) - sum(f(in,t)) == sum(reach(:,t)) - reach(i,t)];
                else
                    Constraints = [Constraints, sum(f(out,t)) - sum(f(in,t)) == -reach(i,t)];
                end
                Constraints = [Constraints, reach(i,t) <= s_comm(i,t)];
            end

            Constraints = [Constraints, reach(C1_idx,t) == 1];
        end
    else
        % Communication-free case
        Constraints = [Constraints, s_comm == 1, reach == 1];
    end

    % Control reachability for devices and switches
    if use_comm
        dg_src = find(strcmp(comm_nodes, src_map('DG')));
        pv_src = find(strcmp(comm_nodes, src_map('PV')));
        wt_src = find(strcmp(comm_nodes, src_map('WT')));
        ess_src = find(strcmp(comm_nodes, src_map('ESS')));

        for t = 1:T
            Constraints = [Constraints, P_DG(t) <= DG.Pmax*reach(dg_src,t)];
            Constraints = [Constraints, P_PV(t) <= PV.Prated*reach(pv_src,t)];
            Constraints = [Constraints, P_WT(t) <= WT.Prated*reach(wt_src,t)];
            Constraints = [Constraints, abs(P_ESS(t)) <= ESS.Pmax*reach(ess_src,t)];
        end

        sw_keys = keys(switch_line_ids);
        for k = 1:numel(sw_keys)
            key = sw_keys{k};
            line_id = switch_line_ids(key);
            src = switch_src(key);
            src_idx = find(strcmp(comm_nodes, src));
            for t = 1:T
                Constraints = [Constraints, y(line_id,t) <= reach(src_idx,t)];
            end
        end
    end

    % Power flow constraints (LinDistFlow)
    for t = 1:T
        for l = 1:L
            i = from(l); j = to(l);
            % Voltage drop
            Constraints = [Constraints, V(j,t) == V(i,t) - 2*(R(l)*P(l,t) + X(l)*Q(l,t)) + (1 - y(l,t))*0];
            % Flow bounds when line open -> zero flow
            M = 1e4;
            Constraints = [Constraints, -M*y(l,t) <= P(l,t) <= M*y(l,t)];
            Constraints = [Constraints, -M*y(l,t) <= Q(l,t) <= M*y(l,t)];
        end

        % Nodal balance
        for i = 1:nb
            Pin = sum(P(from==i,t)) - sum(P(to==i,t));
            Qin = sum(Q(from==i,t)) - sum(Q(to==i,t));

            Pd = lambda(i,t)*P_load(i);
            Qd = lambda(i,t)*Q_load(i);

            Pg = 0; Qg = 0;
            if i == DG.bus
                Pg = P_DG(t); Qg = Q_DG(t);
            end
            if i == PV.bus
                Pg = Pg + P_PV(t);
            end
            if i == WT.bus
                Pg = Pg + P_WT(t);
            end
            if i == ESS.bus
                Pg = Pg + P_ESS(t);
            end

            Constraints = [Constraints, Pin + Pg - Pd == 0];
            Constraints = [Constraints, Qin + Qg - Qd == 0];
        end

        Constraints = [Constraints, Vmin <= V(:,t) <= Vmax];
    end

    % Objective: minimize ENS
    ENS = 0;
    for t = 1:T
        ENS = ENS + sum(omega.*P_load.*(1 - lambda(:,t)))*Delta_t;
    end

    Objective = ENS;

    ops = sdpsettings('solver','gurobi','verbose',0);
    diagnostics = optimize(Constraints, Objective, ops);

    if diagnostics.problem ~= 0
        warning('Optimization issue: %s', diagnostics.info);
    end

    lambda_val = value(lambda);

    P_t = zeros(1,T);
    for t = 1:T
        P_t(t) = sum(omega.*P_load.*lambda_val(:,t)) / sum(omega.*P_load);
    end
    R = mean(P_t);

    res.ENS = value(ENS);
    res.P_t = P_t;
    res.R = R;
end

function idxs = find_link_idx(comm_links, c1, c2)
    idxs = [];
    for k = 1:size(comm_links,1)
        if (strcmp(comm_links{k,1},c1) && strcmp(comm_links{k,2},c2)) || ...
           (strcmp(comm_links{k,1},c2) && strcmp(comm_links{k,2},c1))
            idxs(end+1) = k; %#ok<AGROW>
        end
    end
end

function idxs = find_link_incidence(comm_links, comm_nodes, node_idx, direction)
    idxs = [];
    node = comm_nodes{node_idx};
    for k = 1:size(comm_links,1)
        if strcmp(direction,'out')
            if strcmp(comm_links{k,1}, node)
                idxs(end+1) = k; %#ok<AGROW>
            end
        else
            if strcmp(comm_links{k,2}, node)
                idxs(end+1) = k; %#ok<AGROW>
            end
        end
    end
end
